# Generated by Django 3.2.5 on 2021-07-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='namePrefixes',
            field=models.CharField(choices=[('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=4),
        ),
    ]
